module: CredentialsGoogle
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-CredentialsGoogle/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CredentialsGoogle.xcodeproj, -target, CredentialsGoogle, -toolchain, org.swift.3020160823a, LIBRARY_SEARCH_PATHS=.build/debug]

